PhotoContest/PhotoContest/Controllers/HomeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PhotoContest.Models;
using PhotoContest.Services.Contracts;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PhotoContest.Controllers
{
    public class HomeController : Controller
    {
        private readonly IMapper mapper;
        private readonly IHttpContextAccessor httpContext;
        private readonly IPictureService pictureService;
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger, IPictureService pictureService, IMapper mapper, IHttpContextAccessor httpContext)
        {
            this.mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
            this.httpContext = httpContext;
            this.pictureService = pictureService ?? throw new ArgumentNullException(nameof(pictureService));
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var username = HttpContext.User.Identity.IsAuthenticated;

            var topThreePictureDTO = await this.pictureService.GetTopThreeRatedPictureAsync();

            if (topThreePictureDTO == null)
            {
                return NotFound();
            }

            var bestRatedPicture = mapper.Map<ICollection<PictureFrontViewModel>>(topThreePictureDTO);
            return View(bestRatedPicture);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PhotoContest/PhotoContest/Controllers/PicturesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PhotoContest.Data;
using PhotoContest.Models;
using PhotoContest.Services.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhotoContest.Controllers
{
    public class PicturesController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly IPictureService pictureService;
        private readonly IMapper mapper;
        public PicturesController(IPictureService pictureService, IMapper mapper, UserManager<User> userManager)
        {
            this.pictureService = pictureService ?? throw new ArgumentNullException(nameof(pictureService));
            this.mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
            this.userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
        }
        public async Task<IActionResult> Details(int id)
        {
            var pictureDTO = await this.pictureService.GetPictureAsync(id);

            if (pictureDTO == null)
            {
                return NotFound();
            }

            var pictureModel = mapper.Map<PictureFrontViewModel>(pictureDTO);
            double avScore = 0;

            foreach (var item in pictureDTO.PictureReviews)
            {
                avScore += item.Score;
            }

            pictureModel.PictureReviews.Select(x => x.Score).Sum().ToString().Where(x => x.Equals(avScore / pictureDTO.PictureReviews.Count()));

            return View(pictureModel);
        }

        

    }
}

PhotoContest/PhotoContest/Views/Home/Index.cshtml
@model ICollection<PhotoContest.Models.PictureFrontViewModel>
@{ ViewData["Title"] = "Home Page"; }

@if (!User.IsInRole("Admin")&&!User.IsInRole("User"))
 {
    <div class="text-center">
        <a class="button1" onclick="window.location.href='Identity/Account/Login'">Explore In A Flash</a>
  </div>
}







    <style>
        body {
            background-image: url('https://images.wallpaperscraft.com/image/ocean_view_from_above_surf_125922_1440x900.jpg');
    background-repeat: no-repeat;
            background-attachment: fixed;
    background-size: cover;
        }
    </style>
    @*Top 3 Rated Beers of the month*@
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-sm-4">
                <div class="card" style="width: 18rem;">
                    <img src="@item.Url" class="card-img-top" alt="default-beer-picture">
                    <div class="card-body">
                        <h3 class="card-title"><b>@item.Name</b></h3>
                        <h4 class="card-title"> @item.Story</h4>
                        <p class="card-text"><b>@item.Name</b> is one of our top rated pictures </p>
                        <a class="btn btn-primary btn-sm" asp-controller="Pictures" asp-action="Details" asp-route-id="@item.Id">View picture</a>
                    </div>
                </div>
            </div>}
    </div>