PhotoContest/PhotoContest/Controllers/ContestsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using PhotoContest.Models;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using PhotoContest.Models;
using PhotoContest.Services.Contracts;
using PhotoContest.Services.DTOs;
using PhotoContest.Services.Exceptions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using PhotoContest.Data;

namespace PhotoContest.Controllers
{
    public class ContestsController : Controller
    {
        private readonly IMapper mapper;
        private readonly IContestService contestService;
        private readonly IPhaseService phaseService;
        private readonly IContestStateService contestStateService;
        private readonly IContestCategoryService contestCategoryService;
        private readonly UserManager<User> userManager;

        public ContestsController(UserManager<User> userManager, IContestService contestService, IPhaseService phaseService, IContestStateService contestStateService, IContestCategoryService contestCategoryService, IMapper mapper)
        {

            this.mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
            this.contestService = contestService;
            this.phaseService = phaseService;
            this.contestStateService = contestStateService;
            this.contestCategoryService = contestCategoryService;
            this.userManager = userManager;

        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Categories = await this.contestCategoryService
                    .GetAllContestCategoriesAsync();

            ViewBag.Phases = await this.phaseService
                .GetAllContestPhasesAsync();

            ViewBag.ContestTypes = await this.contestStateService
                .GetAllContestStatesAsync();

            return View();
        }

        public async Task<IActionResult> Details(int id)
        {
            var contestDTO = await this.contestService.GetContestAsync(id);
            if (contestDTO == null)
            {
                return NotFound();
            }

    

            var userId = userManager.GetUserId(User);

            var user = await userManager.GetUserAsync(User);


            foreach (var picture in contestDTO.Pictures)
            {
                picture.IsReviewable = true;

                foreach (var review in picture.PictureReviews)
                {
                    if (review.JuryContestContestId.ToString().Equals(userId))
                    {
                        picture.IsReviewable = false;
                    }
                }
            }

            var contestModel = mapper.Map<ContestFrontViewModel>(contestDTO);




            contestModel.PhaseStartTime = contestDTO.Phase.StartDate;
            contestModel.PhaseEndTime = contestDTO.Phase.EndDate;
            return View(contestModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ContestCreateFrontViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    model.ContestCategoryPhaseDescription = "Phase One";
                    var contestDTO = mapper.Map<ContestInputDTO>(model);
                    ContestOutputFrontDTO newContest = await this.contestService.CreateAsync(contestDTO);
                    var beerModel = mapper.Map<ContestCreateFrontViewModel>(newContest);

                    return RedirectToAction("Index", "Dashboard");
                }
                catch (ResourseAlreadyExistException)
                {
                    ModelState.AddModelError("Name", "Contest with that name already exist in this application!");
                }
                catch (InvalidParameterException e)
                {
                    ModelState.AddModelError(String.Empty, e.Message);
                }
            }

            return View(model);
        }

        public async Task<IActionResult> Users(int id)
        {
            var userDTO = await this.contestService.SeeContestUsers(id);
            List<UserViewModel> mappedUsers = new List<UserViewModel>();
            foreach(var user in userDTO)
            {
                mappedUsers.Add(mapper.Map<UserViewModel>(user));
            }
            return View(mappedUsers);
        }
    }
}

PhotoContest/PhotoContest/Controllers/ReviewController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using PhotoContest.Models;
using PhotoContest.Services.Contracts;
using PhotoContest.Services.DTOs;
using PhotoContest.Services.Exceptions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhotoContest.Controllers
{
    public class ReviewController : Controller
    {
        public IPictureService pictureService;
        public IReviewService reviewService;
        public IMapper mapper;
        private readonly IToastNotification toastNotification;

        public ReviewController(IReviewService reviewService, IMapper mapper, IPictureService pictureService, IToastNotification toastNotification)
        {
            this.reviewService = reviewService ?? throw new ArgumentNullException(nameof(reviewService));
            this.mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
            this.pictureService = pictureService ?? throw new ArgumentNullException(nameof(pictureService));
            this.toastNotification = toastNotification ?? throw new ArgumentNullException(nameof(toastNotification));

            //this.userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateReview(PictureReviewIFrontViewModel model)
        {
            if (true)//Current user може да прави ревю
            {

            }
            if (ModelState.IsValid)
            {
                try
                {

                    var reviewDTO = mapper.Map<PictureReviewDTO>(model);
                    await this.reviewService.CreatePictureReviewAsync(reviewDTO);
                    this.toastNotification.AddSuccessToastMessage("The review is posted");

                    return RedirectToAction("Details", "Pictures", new { id = model.PictureId });
                }
                catch (InvalidParameterException)
                {
                    this.toastNotification.AddErrorToastMessage("The comment must be between 3 and 500 symbols");
                }

            }
            return RedirectToAction("Details", "Pictures", new { id = model.PictureId });
        }
    }
 
}

PhotoContest/PhotoContest/Views/Contests/Create.cshtml
@model ContestCreateFrontViewModel

@{
    var categories = new SelectList(ViewBag.Categories, "Id", "Name");
    var types = new SelectList(ViewBag.ContestTypes, "Id", "Name");
}

<link rel="stylesheet" href="~/css/Identity/Login.css" />
<div style="margin: 15vh 0rem 0rem 0rem">

    <div class="wrapper fadeInDown">
        <div id="formContent" style="max-width: 60rem !important">
            <form id="account" method="post" enctype="multipart/form-data">
                <div class="fadeIn first" style="margin-top: 1rem;">
                    <h5 style="display: inline-block">Create Contest</h5>
                </div>
                <hr />
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Title"></label>
                    <input asp-for="Title" class="form-control fadeIn second" placeholder="Title" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group fadeIn second">
                    <label asp-for="ContestCategoryId"></label>
                    <select asp-for="ContestCategoryId" asp-items="categories" class="form-control">
                    </select>
                    <span asp-validation-for="@Model.ContestCategoryId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Foreground_Url"></label>
                    <input asp-for="Foreground_Url" class="form-control fadeIn second" placeholder="Cover Url" />
                    <span asp-validation-for="Foreground_Url" class="text-danger"></span>
                </div>
                <div class="form-group fadeIn second">
                    <label asp-for="ContestStateId"></label>
                    <select asp-for="ContestStateId" asp-items="types" class="form-control">
                    </select>
                    <span asp-validation-for="@Model.ContestStateId" class="text-danger"></span>
                </div>
                <h5>Phase I</h5>
                <div class="form-group fadeIn second">
                    <label asp-for="Phases.PhaseOne_EndDate"></label>
                    <input asp-for="Phases.PhaseOne_EndDate" class="form-control">
                    <span asp-validation-for="@Model.Phases.PhaseOne_EndDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <h5>Phase Two Duration</h5>
                    <p>Drag the slider to display the current value.</p>
                    <div class="slidecontainer">
                        <input asp-for="Phases.PhaseTwo_Duration" type="range" min="1" max="24" value="1" class="slider" style="width: 100%" id="myRange">
                        <p>Hours: <span id="demo"></span></p>
                    </div>
                </div>
                <div class="form-group formFooter">
                    <div class="form-group">
                        <button type="submit" asp-action="Create" formmethod="post" class="btn btn-primary fadeIn fourth">Create</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="~/js/slider.js"></script>

PhotoContest/PhotoContest/Views/Contests/Details.cshtml
@model PhotoContest.Models.ContestFrontViewModel
@using Microsoft.AspNetCore.Identity
@using PhotoContest.Data.Models
@{
    ViewData["Title"] = "Contest details";

    Layout = "~/Views/Shared/_Layout.cshtml";
}
@inject SignInManager<User> SignInManager

<section class="section mt-5">
    <div class="container d-flex h-100 flex-column">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="row">
                <div class="col-md-5">
                    <div>
                        <img alt="Picture" class="img-fluid" src="@Model.Foreground_Url" />
                    </div>
                </div>
                <div class="col-md-7 d-flex mt-2">
                    <div>
                        <div class="container">
                            <dl class="row">
                                <dt class="col-sm-10">
                                    Title
                                </dt>
                                <dd class="col-sm-10">
                                    @Model.Title
                                </dd>
                                <dt class="col-sm-10">
                                    Contest Category
                                </dt>
                                <dd class="col-sm-10">
                                    @Model.ContestCategory.Name
                                </dd>
                                @if (Model.PhaseEndTime != DateTime.MaxValue)
                                {
                                    <dt class="col-sm-10">
                                        Phase Start Time
                                    </dt>
                                    <dd class="col-sm-10">
                                        @Model.PhaseStartTime
                                    </dd>

                                    <dt class="col-sm-10">
                                        Phase End Time
                                    </dt>
                                    <dd class="col-sm-10">
                                        @Model.PhaseEndTime
                                    </dd>
                                }
                                else
                                {
                                    <dt class="col-sm-10">
                                       Contest Ended on:
                                    </dt>
                                    <dd class="col-sm-10">
                                        @Model.PhaseStartTime
                                    </dd>
                                }

                            </dl>
                        </div>
                        <hr />

                        <div class="container mt-5">
                            <div class="row">                                                       
                            </div>
                            <hr />
                            <div class="row m-md-1">
                                <div>
                                    <a class="btn btn-secondary btn-sm" asp-controller="Home" asp-action="Index"> Back to dashboard</a>
                                 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@if (Model.ContestCategoryPhaseDescription == "Phase Two")
{
    <div class="row">
        @foreach (var item in Model.Pictures)
        {
            <div class="col-sm-4">
                <div class="card" style="width: 18rem;">
                    <img src="@item.Url" class="card-img-top" alt="default-beer-picture">
                    <div class="card-body">
                        <h3 class="card-title"><b>@item.Name</b></h3>
                        <h4 class="card-title"> @item.Story</h4>
                      

                        @if (item.IsReviewable && User.IsInRole("Admin"))
                        {
                            <button type="button" class="collapsible">Give Review</button>
                            <div class="formContent">
                                <form asp-controller="Review" asp-action="CreateReview" method="post">
                                    <input type="hidden" name="PictureId" value="@item.Id" />

                                    <input type="text" id="@item.PictureReviews.Select(x=>x.Comment)" name=comment><br><br>
                                    

                                    <input type="checkbox" onclick="myFunction(@item.PictureReviews.Select(x=>x.Id)" id="myCheck (@item.PictureReviews.Select(x=>x.Id)" name="DoesntFitsCategoryCheckBox" value="Doesn't fit category">

                                    <select name="score" id="@item.PictureReviews.Select(x=>x.Id).ToString()">
                                        <option value="0">Select a rating</option>
                                        <option value="10">10</option>
                                        <option value="9">9</option>
                                        <option value="8">8</option>
                                        <option value="7">7</option>
                                        <option value="6">6</option>
                                        <option value="5">5</option>
                                        <option value="4">4</option>
                                        <option value="3">3</option>
                                        <option value="2">2</option>
                                        <option value="1">1</option>
                                    </select>

                                    <button type="submit">Give Review</button>
                                </form>
                                @*<partial name="_PartialName" />*@
                            </div>
                        }
                       
                    </div>
                </div>
            </div>
        }
    </div>
}

<style>
    .collapsible {
        background-color: #777;
        color: white;
        cursor: pointer;
        padding: 18px;
        width: 100%;
        border: none;
        text-align: left;
        outline: none;
        font-size: 15px;
    }

        .active, .collapsible:hover {
            background-color: #555;
        }

    .formContent {
        padding: 0 18px;
        display: none;
        overflow: hidden;
        background-color: #f1f1f1;
    }
</style>

<script>
    var coll = document.getElementsByClassName("collapsible");
    var i;

    for (i = 0; i < coll.length; i++) {
        coll[i].addEventListener("click", function () {
            this.classList.toggle("active");
            var content = this.nextElementSibling;
            if (content.style.display === "block") {
                content.style.display = "none";
            } else {
                content.style.display = "block";
            }
        });
    }

    function myFunction(id) {
        console.log(id)
        var checkBox = document.getElementById("myCheck " + id);
        var text = document.getElementById(id);
        if (checkBox.checked == true) {
            text.disabled = true;
            text[0].selected = 'selected'
        } else {
            text.disabled = false;
        }
    }
</script>

PhotoContest/PhotoContest/Views/Contests/Users.cshtml
@model IEnumerable<PhotoContest.Models.UserViewModel>
@using Microsoft.AspNetCore.Identity
@using PhotoContest.Data.Models
@{
    ViewData["Title"] = "Picture details";

    Layout = "~/Views/Shared/_Layout.cshtml";
}
@inject SignInManager<User> SignInManager
@*@if ( Model.PictureReviewFront.Score== null)
    {
        Model.PictureReviewFront.Score = 0.0;
    }*@
 


<table class="table">
    <thead class="thead-light">
        <tr>
            <th>E-Mail</th>
            <th>First Name</th>
            <th>Last Name</th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tbody>
            <tr>
                <td>@item.Email</td>
                <td>@item.FirstName</td>
                <td>@item.LastName</td>
            </tr>
        </tbody>
    }
</table>